language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-24.0.0
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository    
  #licenses:
  #  - 'android-sdk-preview-license-.+'
  #  - 'android-sdk-license-.+'
  #  - 'intel-android-extra-license.+'


# cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
