package pl.openpkw.openpkwmobile.qr;

/**
 * Created by Admin on 28.04.16.
 */
public enum QrIndex {

    TERRITORIAL_CODE(0),
    PERIPHERY_NUMBER(1),
    DISTRICT_NUMBER(2),

    VOTING_CARDS_TOTAL_ENTITLED_TO_VOTE(3),
    VOTING_CARDS_TOTAL_CARDS(4),
    VOTING_CARDS_UNUSED_CARDS(5),
    VOTING_CARDS_REGULAR_VOTERS(6),
    VOTING_CARDS_REPRESENTATIVE_VOTERS(7),
    VOTING_CARDS_CERTIFICATE_VOTERS(8),

    CORRESPONDENCE_VOTING_ISSUEDPACKAGES(9),
    CORRESPONDENCE_VOTING_RECEIVEDREPLYENVELOPES(10),
    CORRESPONDENCE_VOTING_MISSINGSTATEMENT(11),
    CORRESPONDENCE_VOTING_MISSINGSIGNATUREONSTATEMENT(12),
    CORRESPONDENCE_VOTING_MISSINGENVELOPEFORVOTINGCARD(13),
    CORRESPONDENCE_VOTING_UNSEALEDENVELOPE(14),
    CORRESPONDENCE_VOTING_ENVELOPESTHROWNTOBALLOTBOX(15),

    VOTING_CARDS_CARDSFROMBALLOTBOX(16),
    VOTING_CARDS_CARDSFROMENVELOPES(17),
    VOTING_CARDS_INVALID_CARDS(18),
    VOTING_CARDS_VALID_CARDS(19),
    VOTING_CARDS_INVALID_VOTES(20),
    VOTING_CARDS_VALID_VOTES(21),


    CANDIDATES_START(23);

    private int index;

    QrIndex(int index) {
        this.index = index;
    }

    public int getIndex() {
        return index;
    }
}
